sudo: false
language: node_js
before_install:
- npm i -g gitbook-cli@2.3.0
- gitbook install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master